### ISSUE TITLE
details

### ISSUE THREAD

**Issue by itz-dude** [5H4D0WILA/InuStreamWebsite#1]
make details page a little better its just showing half content
![image](https://user-images.githubusercontent.com/108194557/187481237-33487fc7-a630-4b50-9ec1-948bcd571e2a.png)

**Comment by celymyst** [comment]
that is a responsiveness issue, which i will work on once everything else is done

**Comment by itz-dude** [comment]
> that is a responsiveness issue, which i will work on once everything else is done

ohk
